function res = histogramStats(vect)

    res = [...
        min(vect),...
        max(vect),...
        median(vect),...
        mean(vect),...
        std(vect),...
        skewness(vect),...
        kurtosis(vect),...
        entropy(vect)...
    ];

end