function res = lesionWaveletStat(image, mask, w_name, w_level)

    lesion = image .* mask;

    [c,s] = wavedec2(lesion,w_level,w_name);
    vect = c(1:s(1,1)*s(1,2))/100000;
    
    res = [...
        min(vect),...
        max(vect),...
        median(vect),...
        mean(vect),...
        std(vect),...
        skewness(vect),...
        kurtosis(vect),...
        entropy(vect)...
    ];
    
end