function res = lesionCoocurenceStat(image, mask, lower_thresh, upper_thresh, lenght, distance)

    lesion = image .* mask;
    
    cooc = graycomatrix(lesion,...
        'GrayLimits',[lower_thresh upper_thresh],...
        'NumLevels',lenght,...
        'Offset', distance);
    feat = GLCM_Features1(cooc,0);

    res = [feat.autoc feat.contr feat.corrm feat.corrp feat.cprom feat.cshad feat.denth feat.dissi ...
        feat.dvarh feat.energ feat.entro feat.homom feat.homop feat.idmnc feat.indnc feat.inf1h ...
        feat.inf2h feat.maxpr feat.savgh feat.senth feat.sosvh feat.svarh];

end