function res = lesionGaborStat(image, mask, filterScales, filterOrientations, filterRows, filterCols, downsamplingRows, downsamplingCols)

    lesion = image .* mask;

    gaborArray = gaborFilterBank(filterScales,filterOrientations,filterRows,filterCols);
    gaborMatrix = gaborFeatures(lesion,gaborArray,downsamplingRows,downsamplingCols);
       
    res = gaborMatrix(:);
    res = [...
        min(gaborMatrix(:)),...
        max(gaborMatrix(:)),...
        median(gaborMatrix(:)),...
        mean(gaborMatrix(:)),...
        std(gaborMatrix(:)),...
        skewness(gaborMatrix(:)),...
        kurtosis(gaborMatrix(:)),...
        entropy(gaborMatrix(:))...
    ];
    
end