function res = lesionStat(image,mask) 

    % vectorize
    vect = image(1 == mask(:));

    res = [...
        min(vect),...
        max(vect),...
        median(vect),...
        mean(vect),...
        std(vect),...
        skewness(vect),...
        kurtosis(vect),...
        entropy(vect)...
    ];
    
end